name: open_file_platform_interface
description:  A common platform interface for the open_file plugin.
repository: https://github.com/crazecoder/open_file/tree/master/open_file_platform_interface
version: 1.1.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
